---
output: latex_fragment
---

```{R setup, echo = FALSE, results = "asis"}
knitr::opts_chunk$set(## fig.path = "figure/", prompt = TRUE,
                      comment = "")
options(width = 50)
```

In the packages \pkg{reda} and \pkg{reReg}, recurrent event data are represented
using an object of type `Recur` created by the `Recur()` function.  The `Recur`
object is an `S4` class object that bundles together a set of recurrent times,
failure time, and censoring status, allowing users an easy first glance of the
recurrent event data.  The `Recur` object is also used as the formula response
for many key functions in \pkg{reda} and \pkg{reReg}.  The following commands
can be used to create a `Recur` object corresponding to the rehospitalization
data:

```{R, error = TRUE, message = FALSE}
library(reda); library(reReg)
data(readmission, package = "frailtypack")
with(readmission, Recur(t.stop, id, event, death))
```

The `Recur()` internally checks whether the specified data fits into the
recurrent event data framework and detected a possible issue on the data
structure.
<!-- Without these subjects, the `Recur` object is presented by intervals. -->
The `show()` method for `Recur` objects presents recurrent events in intervals,
where events happened at end of the recurrent episodes with censoring due to (or
not) terminal indicated by a trailing `+` (or `*`).
The following prints the `Recur` object for the first five subjects.

```{R}
with(readmission[1:14,], Recur(t.stop, id, event, death))
```
<!-- readmission0 <- subset(readmission, id %in% 1:5) -->
<!-- For a concise printing, up to three recurrent intervals are printed. -->
<!-- Users can modify this by specifying `reda.Recur.maxPrint` in `options()`. -->
