---
output: latex_fragment
---
```{R, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(comment = "")
library(reReg)
options(width = 60)
data(readmission, package = "frailtypack")
df0 <- subset(readmission, !(id %in% c(60, 109, 280)))
obj <- with(df0, Recur(t.stop, id, event, death))
fn <- Recur(t.stop, id, event, death) ~ chemo
```
	
<!--To evaluate the covariate effect on the recurrent event process
and/or the terminal event, the `reReg()` function from the \pkg{reReg} package
fits semiparametric regression models to recurrent event data.-->
The `reReg()` function from the \pkg{reReg} package provides methods to fit
semiparametric regression models to recurrent event data.
A general joint model for the rate function of the recurrent event process and
the hazard function of the failure time can be formulated as follow:
\begin{equation}
\lambda(t) = Z \lambda_0(te^{X^\top\alpha})e^{X^\top\beta};
h(t) = Z h_0(te^{X^\top\eta})e^{X^\top\theta},\label{general}
\end{equation}
where $Z$ is a latent shared frailty variable to account for association between the two types of
outcomes, $\lambda_0(\cdot)$ is the baseline rate function,
$h_0(\cdot)$ is the baseline hazard function, and the regression coefficients
$(\alpha, \eta)$ and $(\beta, \theta)$ correspond to the shape and size parameters 
of the rate function and hazard function, respectively.
In contrast to many shared-frailty models that require a parametric assumption,
<!--so that the likelihood method can be used to estimate the joint model,-->
following the idea of \citet{wang2001analyzing},
the `reReg()` function implements semiparametric estimation procedures that do not require the
knowledge about the frailty distribution.
As a result, the dependence between recurrent events and failure event is left unspecified
and the proposed implementations accommodate informative censoring.

Model \eqref{general} includes several popular semiparametric models as special cases,
which can be specified via the `method` argument with the 
rate function and hazard function separated by "`|`".
For examples, the joint Cox model of \citet{huang2004joint} is a special case of
\eqref{general} when $\alpha = \eta = 0$ and can be called by `method = "cox|cox"`;
the joint accelerated mean model of \citet{xu2017joint} is a special case when
$\alpha = \beta$ and $\eta = \theta$ and can be called by `method = "am|am"`.
<!--Another option is `ar` for the accerlated rate model ($\beta = \theta = 0$).-->
<!--When the primary interest is in the covariate effects on the risk of recurrent events and -->
Treating the terminal event as nuisances ($\eta = \theta = 0$),
\eqref{general} reduces to the generalized scale-change model of
\citet{xu2019generalized}, called by `method = "sc|."`.
Moreover, users can mix the models depending on the application.
For example, `method = "cox|ar"` postulate a Cox proportional model for the recurrent event rate
function and an accelerated rate model for the terminal event hazard function
($\alpha = \theta = 0$ in \eqref{general}). 
For inference, the asymptotic variance is estimated from an efficient resampling-based sandwich
estimator motivated by \citet{zeng2008efficient}.
The resampling approach is faster than the conventional bootstrap as it only requires
evaluating perturbed estimating equations rather than solving them.
The following code fits the joint Cox model with 200 (default) resampling replicates.
<!--and the generalized scale-change model, respectively. -->
```{R, cache = TRUE}
fit <- reReg(fn, df0, method = "cox|cox"); summary(fit)
```
<!--The `summary()` method prints the results of the model fits: -->
The model shows that patients treated with chemotherapy are hospitalized less often
(17\% lower) and have a higher risk of death (68\% more) than patients not treated with chemotherapy
though not significant at the 0.05 level.
After a model is fitted, the baseline rate function and hazard function can be visualized
by plotting the `reReg()` object. 
<!--Methods proposed by authors \citet{lin2000semiparametric}, \citet{ghosh2002marginal}, and
\citet{ghosh2003semiparametric} are also implemented in \pkg{reReg}.-->
See \url{wenjie-stat.me/reda/} and \url{www.sychiou.com/reReg/}
for the full package documents.
